home/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='main'),   
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve


urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('project_view/', include('project_view.urls')),
    path('spotify_download/', include('spotify_download.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

project_view/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.views.generic import TemplateView

# https://docs.djangoproject.com/en/3.0/topics/http/urls/
app_name = 'project_view'

urlpatterns = [
    
    path('', views.ClientListView.as_view(), name='main'),
    path('client/create', views.ClientCreateView.as_view(), name='client_create'),
    path('client/<int:pk>/update', views.ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete', views.ClientDeleteView.as_view(), name='client_delete'),
    path('client/<int:pk>', views.ClientDetailView.as_view(), name='client_detail'), 
    
    path('client/<int:pk>/project/<int:pk_proj>', views.ProjectDetailView.as_view(), name='project_detail'), 
    path('client/<int:pk>/project/create', views.ProjectCreateView.as_view(), name='project_create'),
    path('client/<int:pk>/project/<int:pk_proj>/update', views.ProjectUpdateView.as_view(), name='project_update'),
    path('client/<int:pk>/project/<int:pk_proj>/delete', views.ProjectDeleteView.as_view(), name='project_delete'),

    path('project/<int:pk_proj>/module/<int:pk_modu>', views.ModuleDetailView.as_view(), name='module_detail'),
    path('project/<int:pk_proj>/module/create', views.ModuleCreateView.as_view(), name='module_create'),
    path('project/<int:pk_proj>/module/<int:pk_modu>/update', views.ModuleUpdateView.as_view(), name='module_update'),
    path('project/<int:pk_proj>/module/<int:pk_modu>/delete', views.ModuleDeleteView.as_view(), name='module_delete'),

    path('module/<int:pk_modu>/part/<int:pk_part>', views.PartDetailView.as_view(), name='part_detail'),
    path('module/<int:pk_modu>/part/create', views.PartCreateView.as_view(), name='part_create'),
    path('module/<int:pk_modu>/part/<int:pk_part>/update', views.PartUpdateView.as_view(), name='part_update'),
    path('module/<int:pk_modu>/part/<int:pk_part>/delete', views.PartDeleteView.as_view(), name='part_delete'),

    path('part/<int:pk_part>/topic/<int:pk_topi>', views.TopicDetailView.as_view(), name='topic_detail'),
    path('part/<int:pk_part>/topic/create', views.TopicCreateView.as_view(), name='topic_create'),
    path('part/<int:pk_part>/topic/<int:pk_topi>/update', views.TopicUpdateView.as_view(), name='topic_update'),
    path('part/<int:pk_part>/topic/<int:pk_topi>/delete', views.TopicDeleteView.as_view(), name='topic_delete'),
    path('topic/<int:pk_topi>/cancel', views.TopicCancelView.as_view(), name='topic_cancel'),
    path('part/<int:pk_part>/topic/<int:pk_topi>/entry/<int:pk>/update', views.TopicEntryUpdateView.as_view(), name='topic_entry_update'),


    path('topic/<int:pk_topi>/add_pic', views.AddPictureView.as_view(), name='picture_add'),
    path('topic/<int:pk_topi>/picture/<int:pk_pict>', views.stream_file, name='picture_stream'),
    path('topic/<int:pk_topi>/picture/<int:pk_pict>/del_pic', views.DeletePictureView.as_view(), name='picture_delete'),

    path('fixing_list', views.FixingListView.as_view(), name='fixing_list'),
    path('fixing/<int:pk>', views.FixingDetailView.as_view(), name='fixing_detail'),
    path('fixing/create', views.FixingCreateView.as_view(), name='fixing_create'),
    path('fixing/<int:pk>/update', views.FixingUpdateView.as_view(), name='fixing_update'),
    path('fixing/<int:pk>/delete', views.FixingDeleteView.as_view(), name='fixing_delete'),

    path('participant/create', views.ParticipantCreateView.as_view(), name='participant_create'),
    path('participant/<int:pk>/create/<int:pk_for>', views.ParticipantCreate2View.as_view(), name='participant_create2'),
    path('participant/<int:pk>/update', views.ParticipantUpdateView.as_view(), name='participant_update'),
    path('participant/<int:pk>/delete', views.ParticipantDeleteView.as_view(), name='participant_delete'),

    path('participation', views.ParticipationListView.as_view(), name='participation_list'),
    path('participant/<int:pk>/participation/create', views.ParticipationCreateView.as_view(), name='participation_create'),
    path('project/<int:pk_proj>/participation/create', views.ParticipationPrjCreateView.as_view(), name='participation_proj_create'),
    path('participation/<int:pk>/update', views.ParticipationUpdateView.as_view(), name='participation_update'),
    path('participation/<int:pk>/delete', views.ParticipationDeleteView.as_view(), name='participation_delete'),

    path('entries', views.EntryListView.as_view(), name='entries_list'),
    path('topic/<int:pk_topi>/create', views.EntryCreateView.as_view(), name='entry_create'),
    path('entry/<int:pk>/update', views.EntryUpdateView.as_view(), name='entry_update'),
    path('entry/<int:pk>/delete', views.EntryDeleteView.as_view(), name='entry_delete'),

    
    path('part/<int:pk_part>/fix/create', views.FixCreateView.as_view(), name='fix_create'),
    path('part/<int:pk_part>/fix/<int:pk>/update', views.FixUpdateView.as_view(), name='fix_update'),
    path('part/<int:pk_part>/fix/<int:pk>/delete', views.FixDeleteView.as_view(), name='fix_delete'),

    path('part/<int:pk>/mypart', views.MypartView.as_view(), name='mypart'),
    path('part/<int:pk>/unmypart', views.UnmypartView.as_view(), name='unmypart'),

    path('todo/create', views.TodoCreateView.as_view(), name='todo_create'),
    path('todo/<int:pk>/update', views.TodoUpdateView.as_view(), name='todo_update'),
    path('todo/<int:pk>/delete', views.TodoDeleteView.as_view(), name='todo_delete'),
    
    path('todo/<int:pk>/status_update', views.StatusUpdateView.as_view(), name='status_update'),
    
    path('get_in_touch', views.GetInTouchView.as_view(), name='get_in_touch'),
    
    path('unsent', views.UnsentView.as_view(), name='unsent'),
]

home/views.py
from django.shortcuts import render
from django.views import View
from django.conf import settings
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView


class HomeView(View):
    def get(self, request):
        print(request.get_host())
        host = request.get_host()
        islocal = host.find('localhost') >= 0 or host.find('127.0.0.1') >= 0
        context = {
            'installed': settings.INSTALLED_APPS,
            'islocal': islocal
        }
        return render(request, 'home/main.html', context)

home/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Security-Policy" content="
    default-src 'none';
    style-src https://ajax.googleapis.com/ https://maxcdn.bootstrapcdn.com https://code.jquery.com https://use.fontawesome.com 'self' 'unsafe-inline';
    script-src https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js
    https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js
    https://code.jquery.com/ui/1.12.1/jquery-ui.js 'self' 'unsafe-inline';
    font-src https://use.fontawesome.com 'self' https://maxcdn.bootstrapcdn.com;
    img-src 'self' data:;
    object-src 'none';
    connect-src 'self';
    form-action 'self';
    base-uri 'none';">
    <!-- Edit settings.py and add APP_NAME = 'app_name' -->
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
    crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    integrity="sha384-vhJnz1OVIdLktyixHY4Uk3OHEwdQqPppqYR8+5mjsauETgLOcEynD9oPHhhz18Nw"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  integrity="sha384-JPbtLYL10d/Z1crlc6GGGGM3PavCzzoUJ1UxH0bXHOfguWHQ6XAWrIzW+MBGGXe5"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">


{% block head %} {% endblock %}

</head>
<body>
<style>
    .container {
        margin-bottom: 30px;
    }
</style>
<div class="container"> 
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

home/templates/base_menu.html
{% extends "base_bootstrap.html" %}
{% block navbar %}
{% load app_tags %} <!--gravatar (templatetags folder)-->
{% load static %}

<style>
.footer_holder {
  position: fixed;
  left: 0;
  bottom: 0;
  width: 100%;
}
</style>


<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>
    </div>
    <!-- https://stackoverflow.com/questions/22047251/django-dynamically-get-view-url-and-check-if-its-the-current-page -->
    <ul class="nav navbar-nav">
      {% url 'project_view' as project_view %}
      <li {% if request.get_full_path == project_view %}class="active"{% endif %}>
          <a href="{% url 'project_view:main' %}">ProjectView</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="https://github.com/stachusmith/mysite" target="_blank" rel="noopener noreferrer">
        <img src="{% static 'project_view/GitHub-Mark-Light-32px.png' %}" style="width: auto; height: 25px;" alt="GitHub icon">
      </a></li> 
      <li><a href="https://www.linkedin.com/in/stanis%C5%82aw-smith-49b6731b3/" target="_blank" rel="noopener noreferrer">
        <img src="{% static 'project_view/LI-In-Bug.png' %}" style="width: auto; height: 25px;" alt="LinkedIn icon">
      </a></li>
      {% if user.is_authenticated %}
      <li><a href="{% url 'project_view:get_in_touch' %}">get in touch</a></li>
      
      <li class="dropdown">
          <a href="#" data-toggle="dropdown" class="dropdown-toggle">{{ user.username }}</a>
          <ul class="dropdown-menu">
              <li><a href="{% url 'logout' %}?next={% url 'home:main' %}">Logout</a></li>
          </ul>
      </li>
      {% else %}
      <li><a href="{% url 'login' %}">get in touch</a></li>
      <li>
      <a href="{% url 'login' %}?next={% url 'home:main' %}">Login</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>
<div class="footer_holder">
<footer class="bg-light text-center text-lg-start">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgb(230, 230, 230)">
    <a href="{% url 'login' %}">get in touch form</a> | stackoosmith@gmail.com | 
    <a href="https://github.com/stachusmith/mysite" target="_blank" rel="noopener noreferrer">
      <img src="{% static 'project_view/GitHub-Mark-32px.png' %}" style="width: auto; height: 18px;" alt="GitHub icon">
    </a> 
    <a href="https://www.linkedin.com/in/stanis%C5%82aw-smith-49b6731b3/" target="_blank" rel="noopener noreferrer">
      <img src="{% static 'project_view/LI-In-Bug.png' %}" style="width: auto; height: 18px;" alt="LinkedIn icon">
    </a>
  </div>
  <!-- Copyright -->
</footer>
</div>

{% endblock %}

home/templates/base_menu_backup.html
{% extends "base_bootstrap.html" %}
{% block navbar %}
{% load app_tags %}
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>
    </div>
    <!-- https://stackoverflow.com/questions/22047251/django-dynamically-get-view-url-and-check-if-its-the-current-page -->
    <ul class="nav navbar-nav">
      {% url 'ads' as ads %}
      <li {% if request.get_full_path == ads %}class="active"{% endif %}>
          <a href="{% url 'ads:main' %}">Ads</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li>
        <a href="{% url 'ads:ad_create' %}">Create Ad</a>
        </li>
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                <img style="width: 25px;" src="{{ user|gravatar:60 }}"/><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'logout' %}?next={% url 'ads:main' %}">Logout</a></li>
            </ul>
        </li>
        {% else %}
        <li>
        <a href="{% url 'login' %}?next={% url 'ads:main' %}">Login</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}

home/templates/base_menu_backup_original.html
{% extends "base_bootstrap.html" %}
{% block navbar %}
{% load app_tags %} <!--gravatar (templatetags folder)-->
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>
    </div>
    <!-- https://stackoverflow.com/questions/22047251/django-dynamically-get-view-url-and-check-if-its-the-current-page -->
    <ul class="nav navbar-nav">
      {% url 'project_view' as project_view %}
      <li {% if request.get_full_path == project_view %}class="active"{% endif %}>
          <a href="{% url 'project_view:main' %}">ProjectView</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li>
            <a href="{% url 'project_view:fixing_list' %}">Manage fixing elements</a>
        </li>
        <li>
            <a href="{% url 'project_view:participation_list' %}">Manage project participants</a>
        </li>
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                <img style="width: 25px;" src="{{ user|gravatar:60 }}"/><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'logout' %}?next={% url 'project_view:main' %}">Logout</a></li>
            </ul>
        </li>
        {% else %}
        <li>
        <a href="{% url 'login' %}?next={% url 'project_view:main' %}">Login</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}

home/templates/base_menu_project_view.html
{% extends "base_bootstrap.html" %}
{% block navbar %}
{% load app_tags %} <!--gravatar (templatetags folder)-->
{% load static %}

<style>
    .subnav {
        display: grid;
        grid-template-columns: 1fr 1fr 1fr 1fr;
        width: 100%;
        height: 30px;
        background-color: gray;
        padding-top: 5px;
        padding-left: 150px;
        padding-right: 10px;
    }
    .subnav_el, .subnav_el:focus{
        text-decoration: none;
        color: white;
    }
    .subnav_el:hover{
        text-decoration: none;
        color: orange;
    }
    #log-button {
        background-color: transparent;
    }
    
    .footer_holder {
    position: fixed;
    left: 0;
    bottom: 0;
    width: 100%;
    }


</style>


<nav class="navbar navbar-default navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>
        </div>
        <!-- https://stackoverflow.com/questions/22047251/django-dynamically-get-view-url-and-check-if-its-the-current-page -->
        <ul class="nav navbar-nav">
        {% url 'project_view' as project_view %}
        <li {% if request.get_full_path == project_view %}class="active"{% endif %}>
            <a href="{% url 'project_view:main' %}">ProjectView</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="https://github.com/stachusmith/mysite" target="_blank" rel="noopener noreferrer">
                <img src="{% static 'project_view/GitHub-Mark-Light-32px.png' %}" style="width: auto; height: 25px;" alt="GitHub icon"></a>
            </li> 
            <li><a href="https://www.linkedin.com/in/stanis%C5%82aw-smith-49b6731b3/" target="_blank" rel="noopener noreferrer">
                <img src="{% static 'project_view/LI-In-Bug.png' %}" style="width: auto; height: 25px;" alt="LinkedIn icon"></a>
            </li>
            
            {% if user.is_authenticated %}
            <li><a href="{% url 'project_view:get_in_touch' %}">get in touch</a></li>
            <li class="dropdown">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle">{{ user.username }}</a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'logout' %}?next={% url 'home:main' %}">Logout</a></li>
                </ul>
            </li>
            {% else %}
            <li><a href="{% url 'login' %}">get in touch</a></li>
            <li>
            <a href="{% url 'login' %}?next={% url 'home:main' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </div>
    <div class="subnav">
        <a href="{% url 'project_view:fixing_list' %}" class="subnav_el" target="_blank" rel="noopener noreferrer">Manage fixing elements <i class="fas fa-external-link-alt" style="font-size: 11px;"></i></a>
        <a href="{% url 'project_view:participation_list' %}" class="subnav_el" target="_blank" rel="noopener noreferrer">Manage project participants <i class="fas fa-external-link-alt" style="font-size: 11px;"></i></a>
        <a href="{% url 'project_view:todo_create' %}" class="subnav_el">to-do list</a>
        <div class="dropdown">
            <a href="#" class="subnav_el" data-toggle="dropdown" class="dropdown-toggle">myParts</a>
            <ul class="dropdown-menu">
                
                {% if my_parts %}
                    {% for my_part in my_parts %}
                        {% if my_part.user == user %}
                            <li>
                                <a href="{% url 'project_view:part_detail' my_part.part.module.id my_part.part.id %}">{{my_part.part.name }} {{ my_part.part.module.project.name }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    empty :(
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="footer_holder">
    <footer class="bg-light text-center text-lg-start">
      <!-- Copyright -->
      <div class="text-center p-3" style="background-color: rgb(230, 230, 230)">
        <a href="{% url 'project_view:get_in_touch' %}">get in touch form</a> | stackoosmith@gmail.com | 
        <a href="https://www.linkedin.com/in/stanis%C5%82aw-smith-49b6731b3/" target="_blank" rel="noopener noreferrer">
          <img src="{% static 'project_view/LI-In-Bug.png' %}" style="width: auto; height: 18px;" alt="LinkedIn icon">
        </a> | 
        <a href="https://github.com/stachusmith/mysite" target="_blank" rel="noopener noreferrer">
            <img src="{% static 'project_view/GitHub-Mark-32px.png' %}" style="width: auto; height: 18px;" alt="GitHub icon">
        </a>
      </div>
      <!-- Copyright -->
    </footer>
    </div>
{% endblock %}