home/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='main'),   
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve


urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('project_view/', include('project_view.urls')),
    path('spotify_download/', include('spotify_download.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

project_view/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.views.generic import TemplateView

# https://docs.djangoproject.com/en/3.0/topics/http/urls/
app_name = 'project_view'

urlpatterns = [
    
    path('', views.ClientListView.as_view(), name='main'),
    path('client/create', views.ClientCreateView.as_view(), name='client_create'),
    path('client/<int:pk>/update', views.ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete', views.ClientDeleteView.as_view(), name='client_delete'),
    path('client/<int:pk>', views.ClientDetailView.as_view(), name='client_detail'), 
    
    path('client/<int:pk>/project/<int:pk_proj>', views.ProjectDetailView.as_view(), name='project_detail'), 
    path('client/<int:pk>/project/create', views.ProjectCreateView.as_view(), name='project_create'),
    path('client/<int:pk>/project/<int:pk_proj>/update', views.ProjectUpdateView.as_view(), name='project_update'),
    path('client/<int:pk>/project/<int:pk_proj>/delete', views.ProjectDeleteView.as_view(), name='project_delete'),

    path('project/<int:pk_proj>/module/<int:pk_modu>', views.ModuleDetailView.as_view(), name='module_detail'),
    path('project/<int:pk_proj>/module/create', views.ModuleCreateView.as_view(), name='module_create'),
    path('project/<int:pk_proj>/module/<int:pk_modu>/update', views.ModuleUpdateView.as_view(), name='module_update'),
    path('project/<int:pk_proj>/module/<int:pk_modu>/delete', views.ModuleDeleteView.as_view(), name='module_delete'),

    path('module/<int:pk_modu>/part/<int:pk_part>', views.PartDetailView.as_view(), name='part_detail'),
    path('module/<int:pk_modu>/part/create', views.PartCreateView.as_view(), name='part_create'),
    path('module/<int:pk_modu>/part/<int:pk_part>/update', views.PartUpdateView.as_view(), name='part_update'),
    path('module/<int:pk_modu>/part/<int:pk_part>/delete', views.PartDeleteView.as_view(), name='part_delete'),

    path('part/<int:pk_part>/topic/<int:pk_topi>', views.TopicDetailView.as_view(), name='topic_detail'),
    path('part/<int:pk_part>/topic/create', views.TopicCreateView.as_view(), name='topic_create'),
    path('part/<int:pk_part>/topic/<int:pk_topi>/update', views.TopicUpdateView.as_view(), name='topic_update'),
    path('part/<int:pk_part>/topic/<int:pk_topi>/delete', views.TopicDeleteView.as_view(), name='topic_delete'),
    path('topic/<int:pk_topi>/cancel', views.TopicCancelView.as_view(), name='topic_cancel'),
    path('part/<int:pk_part>/topic/<int:pk_topi>/entry/<int:pk>/update', views.TopicEntryUpdateView.as_view(), name='topic_entry_update'),


    path('topic/<int:pk_topi>/add_pic', views.AddPictureView.as_view(), name='picture_add'),
    path('topic/<int:pk_topi>/picture/<int:pk_pict>', views.stream_file, name='picture_stream'),
    path('topic/<int:pk_topi>/picture/<int:pk_pict>/del_pic', views.DeletePictureView.as_view(), name='picture_delete'),

    path('fixing_list', views.FixingListView.as_view(), name='fixing_list'),
    path('fixing/<int:pk>', views.FixingDetailView.as_view(), name='fixing_detail'),
    path('fixing/create', views.FixingCreateView.as_view(), name='fixing_create'),
    path('fixing/<int:pk>/update', views.FixingUpdateView.as_view(), name='fixing_update'),
    path('fixing/<int:pk>/delete', views.FixingDeleteView.as_view(), name='fixing_delete'),

    path('participant/create', views.ParticipantCreateView.as_view(), name='participant_create'),
    path('participant/<int:pk>/create/<int:pk_for>', views.ParticipantCreate2View.as_view(), name='participant_create2'),
    path('participant/<int:pk>/update', views.ParticipantUpdateView.as_view(), name='participant_update'),
    path('participant/<int:pk>/delete', views.ParticipantDeleteView.as_view(), name='participant_delete'),

    path('participation', views.ParticipationListView.as_view(), name='participation_list'),
    path('participant/<int:pk>/participation/create', views.ParticipationCreateView.as_view(), name='participation_create'),
    path('project/<int:pk_proj>/participation/create', views.ParticipationPrjCreateView.as_view(), name='participation_proj_create'),
    path('participation/<int:pk>/update', views.ParticipationUpdateView.as_view(), name='participation_update'),
    path('participation/<int:pk>/delete', views.ParticipationDeleteView.as_view(), name='participation_delete'),

    path('entries', views.EntryListView.as_view(), name='entries_list'),
    path('topic/<int:pk_topi>/create', views.EntryCreateView.as_view(), name='entry_create'),
    path('entry/<int:pk>/update', views.EntryUpdateView.as_view(), name='entry_update'),
    path('entry/<int:pk>/delete', views.EntryDeleteView.as_view(), name='entry_delete'),

    
    path('part/<int:pk_part>/fix/create', views.FixCreateView.as_view(), name='fix_create'),
    path('part/<int:pk_part>/fix/<int:pk>/update', views.FixUpdateView.as_view(), name='fix_update'),
    path('part/<int:pk_part>/fix/<int:pk>/delete', views.FixDeleteView.as_view(), name='fix_delete'),

    path('part/<int:pk>/mypart', views.MypartView.as_view(), name='mypart'),
    path('part/<int:pk>/unmypart', views.UnmypartView.as_view(), name='unmypart'),

    path('todo/create', views.TodoCreateView.as_view(), name='todo_create'),
    path('todo/<int:pk>/update', views.TodoUpdateView.as_view(), name='todo_update'),
    path('todo/<int:pk>/delete', views.TodoDeleteView.as_view(), name='todo_delete'),
    
    path('todo/<int:pk>/status_update', views.StatusUpdateView.as_view(), name='status_update'),
    
    path('get_in_touch', views.GetInTouchView.as_view(), name='get_in_touch'),
    
    path('unsent', views.UnsentView.as_view(), name='unsent'),
]

project_view/models.py
from django.db import models
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
from django.conf import settings

# one to many:

class GetInTouch(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(1, "Title must be greater than 1 character")])
    sent = models.IntegerField(null=True)

    def __str__(self):
        return self.name


class Development_provider(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(1, "Title must be greater than 1 character")])
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

class Job_title(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(1, "Title must be greater than 1 character")])
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

class Client(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(1, "Title must be greater than 1 character")])
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

class Supplier(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(1, "Title must be greater than 1 character")])

    def __str__(self):
        return self.name

class Project(models.Model):
    name = models.CharField(
            max_length=200,
            unique=True,
            validators=[MinLengthValidator(1, "Title must be greater than 1 character")])

    client = models.ForeignKey(Client, on_delete=models.CASCADE, null=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ['name']
    def __str__(self):
        return self.name

class Participant(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(1, "Title must be greater than 1 character")])

    phone_number = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(blank=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, null=True, blank=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, null=True, blank=True)
    development_provider = models.ForeignKey(Development_provider, on_delete=models.CASCADE, null=True, blank=True)
    job_title = models.ForeignKey(Job_title, on_delete=models.CASCADE, null=True, blank=True)
    project = models.ManyToManyField(Project, through='Participation', related_name='participation_project_view')
    
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    def __str__(self):
        return self.name



class Module(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(1, "Title must be greater than 1 character")])

    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name



class Fixing(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(1, "Title must be greater than 1 character")])
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class Status(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(1, "Title must be greater than 1 character")])
    def __str__(self):
        return self.name

class Check_box(models.Model):
    state = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(1, "Title must be greater than 1 character")])
    def __str__(self):
        return self.state
    

# main model:

class Part(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")])

    material = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")],
            blank=True)
    
    module = models.ForeignKey(Module, on_delete=models.CASCADE)
          
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, blank=True, null=True)
    
    fixing_element = models.ManyToManyField(Fixing, through='Fix', related_name='fixing_project_view')

    thickness = models.FloatField(null=True)

    minimal_draft_angle = models.FloatField(null=True)

    my_parts = models.ManyToManyField(settings.AUTH_USER_MODEL, through='My_part', related_name='my_parts_project_view')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    class Meta:
        ordering = ['name']
    def __str__(self):
        return self.name

class Topic(models.Model):
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(1, "Title must be greater than 1 character")])
    
    description = models.TextField(max_length=255, null=True, blank=True)

    part = models.ForeignKey(Part, on_delete=models.CASCADE, null=True)

    status = models.ForeignKey(Status, on_delete=models.CASCADE, null=True)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    date_of_creation = models.DateField(auto_now_add=True)
    last_modified = models.DateField(auto_now=True)
    class Meta:
        ordering = ['date_of_creation']
    def __str__(self):
        return self.title

class Todo(models.Model):
    description = models.TextField(max_length=255, null=True, blank=True)

    status = models.ForeignKey(Status, on_delete=models.CASCADE, null=True)

    app_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='involved_user')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    date_of_creation = models.DateField(auto_now_add=True)

    deadline = models.DateField()
    
    last_modified = models.DateField(auto_now=True)
    #class Meta:
    #    ordering = ['deadline']
    def __str__(self):
        return self.description[:20]

class Entry(models.Model):
    date_of_entry = models.DateField(auto_now_add=True)
    last_modified = models.DateField(auto_now=True)
    deadline = models.DateField()
    problem_description = models.TextField()
    solution = models.TextField()
    responsible = models.ManyToManyField(Participant, through='Responsibility', related_name='responsible_participants')
    #responsible = models.ForeignKey(Participant, on_delete=models.CASCADE, related_name='responsible_participants')
    involved = models.ManyToManyField(Participant, related_name='involved_participants')
    agreed_with = models.ManyToManyField(Participant, related_name='agreed_with_participants')
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
class Picture(models.Model):
    picture = models.BinaryField(null=True, blank=True, editable=True)

    content_type = models.CharField(max_length=256, null=True, blank=True, help_text='The MIMEType of the file')

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=True)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    session = models.IntegerField(null=True)

# many to many:

class Participation(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    participant = models.ForeignKey(Participant, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    class Meta:
        unique_together = ('project', 'participant')

class Responsibility(models.Model):
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE)
    participant = models.ForeignKey(Participant, on_delete=models.CASCADE)


class Fix(models.Model):
    
    number_of_elements = models.IntegerField(null=True)
    part = models.ForeignKey(Part, on_delete=models.CASCADE)
    fixing = models.ForeignKey(Fixing, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # https://docs.djangoproject.com/en/3.0/ref/models/options/#unique-together
    class Meta:
        unique_together = ('part', 'fixing')


# admin:
    def __str__(self) :
        if self.number_of_elements > 1:
            self.fixing.name = f'{self.fixing.name}s' #plural
        #string in admin
        return '%s has %s %s'%(self.part, self.number_of_elements, self.fixing.name)

class My_part(models.Model):
    part = models.ForeignKey(Part, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # https://docs.djangoproject.com/en/3.0/ref/models/options/#unique-together
    class Meta:
        unique_together = ('part', 'user')










    

    

project_view/templates/project_view/client_confirm_delete.html
{% extends "base_menu_project_view.html" %}
{% block content %}
<h1>Delete Client</h1>

<p>Are you sure you want to delete the following client? {{ client }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" value="Cancel" onclick="window.location.href='{% url 'project_view:main' %}'; return false;">
</form>
{% endblock %}

project_view/templates/project_view/get_in_touch_form.html
{% extends "base_menu_project_view.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'project_view/login.css' %}">
<script type="text/javascript" src="{% static 'project_view/project_view.js' %}"></script>


<p>
  <form action="{% url 'project_view:get_in_touch' %}" method="post">
    <div class="upper_form">
      {% csrf_token %}
      {{ touch_form |crispy }}
    </div>
    <div class="lower_form">
      {% csrf_token %}
      {{ touch_form2 |crispy }}
    </div>
    
    <div class="button">
      <input type="submit" value="Send">
      <input type="submit" value="Cancel" onclick="window.location.href='{% url 'home:main' %}'; return false;">
    </div>
  </form>
</p>
<script>
  var myUrl = '{% url 'project_view:unsent' %}'

  window.onload = function unsentPost(){

    const csrftoken = getCookie('csrftoken');
    const request = new Request (myUrl);
    /*send the data using fetch method:*/
    fetch(request, {
        method: "post",
        mode: 'same-origin',
        headers: {'X-CSRFToken': csrftoken}
    }).then(function(data){
        console.log(data)
    }).catch(console.log(myUrl, 'error'));
}
</script>
{% endblock %}

project_view/templates/project_view/module_detail.html
{% extends "base_menu_project_view.html" %}
{% block content %}
{% load static %}
<link id="stylesheet" rel="stylesheet" type="text/css" href="{% static 'project_view/structure.css' %}">
<script type="text/javascript" src="{% static 'project_view/project_view.js' %}"></script>


<div class="left_block">
  <h4><a href="{% url 'project_view:main' %}">OEMs /</a></h4>
  <h3><a href="{% url 'project_view:client_detail'  client.id %}">{{ client.name }} /</a></h3>
  <h2><a href="{% url 'project_view:project_detail'  client.id project.id %}">{{ project.name }} /</a></h2>
  <h1>{{ module.name }}:</h1>

  <p>
  {% if part_list %}
  <ul class="item_list">
    {% for part in part_list %}
      <div class="items_container">
        <a href="{% url 'project_view:part_detail' module.id part.id %}">{{ part.name }}</a>
        <div id="edit_delete_myparts">
          <div class="edit_delete">
            {% if part.owner == user %}
              <a href="{% url 'project_view:part_update' module.id part.id %}">Edit</a> |
              <a href="{% url 'project_view:part_delete' module.id part.id %}">Delete</a>
            {% endif %}
          </div>
          {% if user.is_authenticated and part.owner == user %}
          <div href="#" id="my_cog{{ part.id }}" title="add to my parts" 
                onclick="myPartPost('{% url 'project_view:mypart' part.id %}', {{ part.id }}); return false;"
                {% if part.id in my_parts_ids %} style="display: none;"
                {% else %}
                  style="display: block;"
                {% endif %}><a href="#"><i class="fa fa-cog" style="color: lightgray; font-size: 20px;"></i></a></div>
          
          <div  id="my_cog_blue{{ part.id }}" title="remove from my parts"
                onclick="myPartPost('{% url 'project_view:unmypart' part.id %}', {{ part.id }}); return false;"
                {% if part.id not in my_parts_ids %} style="display: none;"
                {% else %}
                  style="display: block;"
                {% endif %}><a href="#"><i class="fa fa-cog" style="color: blue; font-size: 20px;"></i></a></div>
        {% endif %}
        </div>
      </div>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no parts for this module.</p>
  {% endif %}
  </p>
  <p>
  <a href="{% url 'project_view:part_create' module.id %}">Add a Part</a>
  </p>

<script>
  function myPartPost(myUrl, part_id) {
    /*prepare data to be sent to server*/
    var formData = new FormData();
    formData.append("inpFile", part_id); //(name of data, data)
    /*prepare data to be sent to server*/
  
    /*send the data using fetch method:*/
    const csrftoken = getCookie('csrftoken');
    fetch(myUrl, {
        method: "post",
        body: formData,
        headers: {'X-CSRFToken': csrftoken}
    }).then(function(data){
        console.log(data)
    }).catch(console.log(myUrl, 'error'));
    var grayCog = document.getElementById("my_cog"+part_id);
    if (grayCog.style.display=="none") {
      grayCog.style.display="block";
    }
    else {
      grayCog.style.display="none";
    }
    var blueCog = document.getElementById("my_cog_blue"+part_id);
    if (blueCog.style.display=="none") {
      blueCog.style.display="block";
    }
    else {
      blueCog.style.display="none"
    }
  }
  </script>

{% endblock %}

project_view/templates/project_view/participation_list.html
{% extends "base_menu_project_view.html" %}
{% block content %}

<style>
.person_grid{
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  grid-gap: 5px;
  margin-bottom: 5px;
}  
.person_box{
  border-color: lightgray;
  border-style: solid;
  border-width: 1px;
  border-radius: 5px;
  padding: 5px;
}

.person_box:hover{
  transform: scale(1.02);
}
.project_list{
  margin-bottom: 5px;
}

.list_line{
  display: flex;
  flex-direction: row;
  justify-content: space-between;
}

.list_line:nth-child(odd){
  background-color: rgb(246, 246, 246);
}

</style>

<h1>All Participants:</h1>
<p>
  <a href="{% url 'project_view:participant_create' %}">Add new participant</a>
</p>

<div class="person_grid">
  {% if project_collection %}
    {% for person, participation_list in project_collection.items %}
      <div class="person_box">
        <div class="name_line">
          {% if person.owner == user %}
            <h3><a href="{% url 'project_view:participant_update' person.id %}">{{ person.name }}</a></h3>
          {% else%}
            <h3>{{ person.name }}</h3>
          {% endif %}
        </div>
        <div class="person_details_container">
          <div class="project_list">
            <div class="list_line">
              <div class="project">
                <ul style="list-style: none; padding-left: 5px;">
                  <li>
                    works for:
                  </li>
                  <li>
                    works as:
                  </li>
                  <li>
                    phone number:
                  </li>
                  <li>
                    email:
                  </li>
                </ul>
              </div>
              <div class="edit_delete">
                <ul style="list-style: none;">
                  <li>
                    {% if person.client %}
                    {{ person.client }}
                    {% endif %}
                    {% if person.supplier %}
                    {{ person.supplier }} 
                    {% endif %}
                    {% if person.development_provider %}
                    {{ person.development_provider }}
                    {% endif %}
                  </li>
                  <li>
                    {{ person.job_title }}
                  </li>
                  <li>
                    {{ person.phone_number}}
                  </li>
                  <li>
                    {{ person.email }}
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="project_list">
          in following projects:
          {% for participation in participation_list %}
            <div class="list_line">
              <div class="project">
                <a href="{% url 'project_view:project_detail' participation.project.client.id participation.project.id %}">{{ participation.project.name }}</a>
              </div>
              <div class="edit_delete">
                {% if participation.owner == user %}

                <a style="color: rgb(140, 0, 255);" href="{% url 'project_view:participation_update' participation.id %}">edit</a> |
                <a style="color: rgb(140, 0, 255);" href="{% url 'project_view:participation_delete' participation.id %}">remove from project</a>

                {% endif %}
              </div>
            </div>
          {% endfor %}
        </div>
        <p>
          <a style="color: green;" href="{% url 'project_view:participation_create' person.id %}">add project</a>
        </p>
      </div>
      
    {% endfor %}
  {% endif %}
</div>
<div>
<p>
  <a href="{% url 'project_view:participant_create' %}">Add new participant</a>
</p>
</div>
{% endblock %}

project_view/templates/project_view/project_detail.html
{% extends "base_menu_project_view.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'project_view/structure.css' %}">


<div class="page">
  <div class="left_block">
    <h3><a href="{% url 'project_view:main' %}">OEMs /</a></h3>
    <h2><a href="{% url 'project_view:client_detail'  client.id %}">{{ client.name }} /</a></h2>
    <h1>{{ project.name }}:</h1>

    <p>
    {% if module_list %}
    <ul class="item_list">
      {% for module in module_list %}
      <div class="items_container">
            <a href="{% url 'project_view:module_detail' project.id module.id %}">{{ module.name }}</a>
            {% if module.owner == user %}
            <div class="edit_delete">
              <a href="{% url 'project_view:module_update' project.id module.id %}">Edit</a> |
              <a href="{% url 'project_view:module_delete' project.id module.id %}">Delete</a>
            </div>
            {% endif %}
      </div>
      {% endfor %}
    </ul>
    {% else %}
      <p>There are no modules for this project.</p>
    {% endif %}
    </p>

    <p>
      <a href="{% url 'project_view:module_create' project.id %}">Add a Module</a>
    </p>
  </div>
  <div class="right_block" id="participants">
    <h2>Participants:</h2>

    {% if project_list %}
      <ul class="item_list">
        {% for project in project_list %}
          <div class="items_container">
            {% if project.participant.owner == user %}
            <a href="{% url 'project_view:participant_update' project.participant.id %}" target="_blank" rel="noopener noreferrer" style="width: 100%;">{{ project.participant.name }} 
              <i class="fas fa-external-link-alt" style="font-size: 11px; float: right;"></i></a>
            {% else %}
            {{ project.participant.name }}
            {% endif %}
          </div>
        {% endfor %}
      </ul>
    {% else %}
        <p>There are no participants in this project.</p>
    {% endif %}
    <p>
      <a href="{% url 'project_view:participant_create' %}" target="_blank" rel="noopener noreferrer" style="width: 100%;">Add new participant 
        <i class="fas fa-external-link-alt" style="font-size: 11px; float: right;"></i></a>
    </p>
    <p>
      <a href="{% url 'project_view:participation_proj_create' project.id %}" target="_blank" rel="noopener noreferrer" style="width: 100%;">Add existing participant 
        <i class="fas fa-external-link-alt" style="font-size: 11px; float: right;"></i></a>
    </p>
    <p>
      <a href="{% url 'project_view:participation_list' %}" target="_blank" rel="noopener noreferrer" style="width: 100%;">Manage participants 
        <i class="fas fa-external-link-alt" style="font-size: 11px; float: right;"></i></a>
    </p>
  </div>
</div>
{% endblock %}

project_view/templates/project_view/project_list.html
{% extends "base_menu.html" %}
{% block content %}

<h1>Projects</h1>

<p>
{% if project_list %}
<ul>
  {% for project in project_list %}
    <li>
        <a href="{% url 'project_view:modules'  project.id %}">{{ client.name }}</a>
        {% if client.owner == user %}
        (<a href="{% url 'project_view:project_update' project.id %}">Edit</a> |
        <a href="{% url 'project_view:project_delete' project.id %}">Delete</a>)
        {% endif %}
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no projects in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'project_view:project_create' %}">Add a Project</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'project_view:main' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'project_view:main' %}">Login</a>
{% endif %}
</p>
{% endblock %}